project_id = "whfjfwxjtujfntwukzih"

[functions.calculate-carbon]
verify_jwt = false

[functions.get-seller-financials]
verify_jwt = true

[functions.get-google-maps-key]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = true

[functions.confirm-dispatch]
verify_jwt = true

[functions.confirm-delivery]
verify_jwt = true

[functions.raise-dispute]
verify_jwt = true

[functions.admin-resolve-dispute]
verify_jwt = true

[functions.create-connect-account]
verify_jwt = true

[functions.check-connect-status]
verify_jwt = true

[functions.generate-environmental-certificate]
verify_jwt = true

[functions.track-blog-view]
verify_jwt = false

[functions.request-account-deletion]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.ensure-transaction-messages]
verify_jwt = true
